[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rewriter"
version = "0.1.0"
authors = [
    {name = "Markis Taylor", email = "m@rkis.net"},
]
description = "Rewrite python code"
readme = "README.md"
requires-python = ">=3.10"
classifiers = []
dependencies = []

[tool.coverage.run]
branch = true
source = [
  "rewriter",
]
omit = [
  "rewriter/__main__.py"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-q"
testpaths = [
  "tests",
]

[tool.black]
target-version = ["py310"]
line-length = 100

[tool.mypy]
packages = ["rewriter", "tests"]
strict = true
mypy_path = "typings"

[tool.setuptools]
py-modules = ["rewriter"]

[tool.ruff]
target-version = "py310"
line-length = 100
select = [ "E", "F", "W", "Q", "UP", "I", "N" ]

[tool.hatch]

[tool.hatch.build.targets.wheel.hooks.mypyc]
dependencies = ["hatch-mypyc"]
mypy-args = ["--ignore-missing-imports"]
