name: python check

on:
  pull_request:

jobs:
  format-check:
    name: format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: markis/python-checker@main
      with:
        cmd: black --check .

  type-check:
    name: type check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: markis/python-checker@main
      with:
        cmd: mypy --install-types --non-interactive .

  lint-check:
    name: lint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: markis/python-checker@main
      with:
        cmd: ruff check .
