name: Build

on: 
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate_wheels_matrix:
    name: Generate wheels matrix
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cibuildwheel and pypyp
        run: |
          pipx install cibuildwheel==2.11.1
          pipx install pypyp==1
      - id: set-matrix
        run: |
          MATRIX=$(
            {
              cibuildwheel --config-file=cibuildwheel.toml --print-build-identifiers --platform linux . \
              | pyp 'json.dumps({"only": x, "os": "ubuntu-latest"})' \
              && cibuildwheel --config-file=cibuildwheel.toml --print-build-identifiers --platform macos . \
              | pyp 'json.dumps({"only": x, "os": "macos-latest"})' \
              && cibuildwheel --config-file=cibuildwheel.toml --print-build-identifiers --platform windows . \
              | pyp 'json.dumps({"only": x, "os": "windows-latest"})'
            } | pyp 'json.dumps(list(map(json.loads, lines)))'
          )
          echo "include=$MATRIX" | tee -a $GITHUB_OUTPUT
        env:
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64

  build_wheels:
    name: Build ${{ matrix.only }}
    needs: generate_wheels_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate_wheels_matrix.outputs.include) }}

    steps:
      - uses: actions/checkout@v3
      - name: Checkout mypy
        shell: bash
        # use a commit hash checked into a file to get the mypy revision to build.
        # submodules prove problematic since .git is outside cibuildwheel's manylinux container
        run: |
          git clone https://github.com/python/mypy.git --recurse-submodules
          git -C mypy checkout $(cat mypy_commit)
      - uses: pypa/cibuildwheel@v2.11.1
        with:
          config-file: cibuildwheel.toml
          package-dir: mypy
          only: ${{ matrix.only }}

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl
