name: Build

on: 
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    name: build sdist + pep518 wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: Install latest pip, build
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build
      - name: Build wheel and source distributions
        run: python -m build

      - name: Upload artifacts as workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: disribution
          path: ./dist/*

  build_wheels:
    name: mypyc wheels (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x86_64
          - os: macos-11
            name: macos-x86_64
            macos_arch: "x86_64"
          - os: macos-11
            name: macos-universal2
            macos_arch: "universal2"

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_ARCHS_MACOS: "${{ matrix.macos_arch }}"

      - name: Upload wheels as workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-mypyc-wheels
          path: ./wheelhouse/*.whl
